name: ''
description: 'Add a new annotated tag on any merge and master commit'
author: Adrien Saunier

inputs:
  rcPrefix:
    description: 'How should we prefix the release candidate tag ?'
    required: false
    default: 'RC'
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/add-release-candidate-tag.sh
      shell: bash
      env:
        RELEASE_CANDIDATE_PREFIX: ${{ inputs.rcPrefix }}
