name: Add RC tag

on:
  push:
    branches:
      - main

jobs:
  tag_release_candidate_on_merge:
    runs-on: ubuntu-latest
    name: Add RC tag
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: Akhilian/xlr8-with-actions@main
